pipeline {
  environment {
    registry = "azirar.ovh:5143/nodify-ui"
  }

  agent any

  tools {
    nodejs "Node"
  }

  stages {
    stage('Install dépendances') {
      steps {
        dir('itexpert-content-ui') {
          sh 'npm install --loglevel=error'
        }
      }
    }

    stage('Build production') {
      steps {
        dir('itexpert-content-ui') {
          sh 'npm run build-prod --loglevel=error'
        }
      }
    }

    stage('Build et Push Image Docker') {
      steps {
        dir('itexpert-content-ui') {
          script {
              def dockerImage = docker.build("${registry}:${BUILD_NUMBER}")
              dockerImage.push() // Push direct sans authentification
          }
        }
      }
    }
  }
}
