services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db
      - mongo-conf:/data/configdb

  nodify-core:
    build:
      dockerfile: Dockerfile-core
    depends_on:
      - mongo
    environment:
      MONGO_URL: "${MONGO_URL}"
      ADMIN_PWD: "${ADMIN_PWD}"
      API_URL: "${API_URL}"
    expose:
      - "8080"

  nodify-api:
    build:
      dockerfile: Dockerfile-api
    depends_on:
      - mongo
    environment:
      MONGO_URL: "${MONGO_URL}"
    expose:
      - "9080"
    ports:
      - 9080:9080

  nodify-ui:
    build:
      dockerfile: Dockerfile-ui
    depends_on:
      - nodify-core
      - nodify-api
    ports:
      - 80:80
    environment:
      CORE_URL: "${CORE_URL}"
      API_URL: "${API_URL}"

volumes:
  mongo:
  mongo-conf:
