services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db
      - mongo-conf:/data/configdb

  nodify-core:
    build:
      dockerfile: Dockerfile-core
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017/nodify"
      ADMIN_PWD: Admin13579++
      API_URL: "http://localhost:9080"
    expose:
      - "8080"

  nodify-api:
    build:
      dockerfile: Dockerfile-api
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017/nodify"
    expose:
      - "9080"
    ports:
      - 9080:9080

  nodify-ui:
    build:
      dockerfile: Dockerfile-ui
    depends_on:
      - nodify-core
      - nodify-api
    ports:
      - 80:80
    environment:
      CORE_URL: "http://nodify-core:8080"
      API_URL: "http://localhost:9080"

volumes:
  mongo:
  mongo-conf:
