spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
      auto-index-creation:  true
    redis:
      url: ${REDIS_URL:redis://localhost:6379}  # prendra la variable d'environnement REDIS_URL ou localhost par défaut
      timeout: 20s    # timeout des opérations Redis (par défaut 1 min)
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          time-between-eviction-runs: 30s
  application:
    name: nodify-headless-cms-core
    version: 3.0.0

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
    #lazy-initialization: true

  jackson:
    default-property-inclusion: non_empty

  springdoc:
    show-actuator: true
    use-management-port: true
    show-login-endpoint: false
    webjars.prefix: ""


management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: openapi,swagger-ui

app:
  defaultLanguages: EN;FR;ES
  admin-user: admin
  admin-password: ${ADMIN_PWD}
  api-url: ${API_URL}

springbootwebfluxjjwt:
  jjwt:
    secret: 908jnNDNKD%%+D++*1°030..W***££%_°°00+/.?????%%%Jnn,ds---))ààuezyzuiuaueyruziu
    expiration: 28800
  password:
    encoder:
      secret: sddfskjnjnsdfdjsdfjjdsb0399¨¨¨%*%++++£%*¨¨¨¨¨//.
      iteration:  33
      keylength:  256
server:
  port : 8080
logging:
  level:
    root: ERROR                              # niveau global
    com.itexpert: INFO                      # ton package principal pour debug
    org.springframework.data.redis: ERROR   # debug Redis (Spring Data Redis)
    io.lettuce.core: ERROR                  # debug Lettuce client (commandes Redis, timeout)
    reactor.netty: ERROR                     # réduire le bruit des logs Netty si trop verbeux
    com.itexpert.content.core.config.SecurityContextRepository: INFO

security:
  auth:
    mode: ${AUTH_MODE:internal} # internal, oauth2, openid

  oauth2:
    enabled: ${OAUTH2_ENABLED:false}
    config:
      authorization-uri: ${OAUTH2_AUTHORIZATION_URI}
      token-uri: ${OAUTH2_TOKEN_URI}
      user-info-uri: ${OAUTH2_USER_INFO_URI}
      client-id: ${OAUTH2_CLIENT_ID}
      client-secret: ${OAUTH2_CLIENT_SECRET}
      scope: ${OAUTH2_SCOPE}
      roles-claim: ${OAUTH2_ROLES_CLAIM}
      user-name-claim: ${OAUTH2_USER_NAME_CLAIM}
      frontend-target-url: ${OAUTH2_FRONTEND_TARGET_URL}
      redirect-uri: ${OAUTH2_REDIRECT_URI}

  openid:
    enabled: ${OPENID_ENABLED:false}
    config:
      issuer-uri: ${OPENID_ISSUER_URI}
      client-id: ${OPENID_CLIENT_ID}
      client-secret: ${OPENID_CLIENT_SECRET}
      jwk-set-uri: ${OPENID_JWK_SET_URI}
      user-info-uri: ${OPENID_USER_INFO_URI}
      authorization-uri: ${OPENID_AUTHORIZATION_URI}
      token-uri: ${OPENID_TOKEN_URI}
      logout-uri: ${OPENID_LOGOUT_URI}
      roles-claim: ${OPENID_ROLES_CLAIM}
      user-name-claim: ${OPENID_USER_NAME_CLAIM}
      frontend-target-url: ${OPENID_FRONTEND_TARGET_URL}
      redirect-uri: ${OPENID_REDIRECT_URI}