spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
      auto-index-creation:  true
    redis:
      url: ${REDIS_URL:redis://localhost:6379}  # prendra la variable d'environnement REDIS_URL ou localhost par défaut
      timeout: 2s    # timeout des opérations Redis (par défaut 1 min)
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          time-between-eviction-runs: 1s
  application:
    name: nodify-headless-cms-core
    version: 3.0.0

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
    #lazy-initialization: true

  jackson:
    default-property-inclusion: non_empty

  springdoc:
    show-actuator: true
    use-management-port: true
    show-login-endpoint: true
    webjars.prefix: ""


management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: openapi,swagger-ui

app:
  defaultLanguages: EN;FR;ES
  admin-user: admin
  admin-password: ${ADMIN_PWD}
  api-url: ${API_URL}

springbootwebfluxjjwt:
  jjwt:
    secret: 908jnNDNKD%%+D++*1°030..W***££%_°°00+/.?????%%%Jnn,ds---))ààuezyzuiuaueyruziu
    expiration: 28800
  password:
    encoder:
      secret: sddfskjnjnsdfdjsdfjjdsb0399¨¨¨%*%++++£%*¨¨¨¨¨//.
      iteration:  33
      keylength:  256
server:
  port : 8080
logging:
  level:
    root: INFO                              # niveau global
    com.itexpert: INFO                      # ton package principal pour debug
    org.springframework.data.redis: DEBUG   # debug Redis (Spring Data Redis)
    io.lettuce.core: DEBUG                  # debug Lettuce client (commandes Redis, timeout)
    reactor.netty: WARN                     # réduire le bruit des logs Netty si trop verbeux