spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
      auto-index-creation:  true
      #database: itexpert-content-db
    redis:
      url: ${REDIS_URL:redis://localhost:6379}  # prendra la variable d'environnement REDIS_URL ou localhost par défaut

  application:
    name: nodify-headless-cms-api
    version: 3.0.0

  main:
    web-appli cation-type: reactive
    allow-bean-definition-overriding: true
    lazy-initialization: true

  jackson:
    default-property-inclusion: non_empty
server:
  port: 1080