name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Cache SonarQube packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    # Build tous les modules
    - name: Build all modules
      run: mvn -B clean install -DskipTests
    
    # Exécuter les tests du module core
    - name: Run tests for core module
      run: mvn -B test -pl itexpert-content-core
    
    # Exécuter les tests du module API
    - name: Run tests for api module
      run: mvn -B test -pl itexpert-content-api
    
    # Analyse SonarQube pour chaque module
    - name: 🔍 SonarQube Scan - Lib
      run: mvn -f itexpert-content-lib/pom.xml sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
    
    - name: 🔍 SonarQube Scan - Core
      run: mvn -f itexpert-content-core/pom.xml sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
    
    - name: 🔍 SonarQube Scan - API
      run: mvn -f itexpert-content-api/pom.xml sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
    
    - name: 🔍 SonarQube Scan - Studio
      run: mvn -f itexpert-content-ui/pom.xml sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
    
    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    # Build and push images
    - name: Build and push Nodify API
      run: |
        docker build -f Dockerfile-api -t ${{ secrets.DOCKER_USERNAME }}/nodify-api:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/nodify-api:latest
    
    - name: Build and push Nodify Core
      run: |
        docker build -f Dockerfile-core -t ${{ secrets.DOCKER_USERNAME }}/nodify-core:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/nodify-core:latest
    
    - name: Build and push Nodify Studio
      run: |
        docker build -f Dockerfile-ui -t ${{ secrets.DOCKER_USERNAME }}/nodify-studio:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/nodify-studio:latest
    
    # Deploy to server
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script_stop: true
        script: |
          cd /home/azirar/docker-compose/nodify
          docker compose pull
          docker compose up -d
          docker image prune -f
