name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Cache SonarQube packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    # Build tous les modules
    - name: Build all modules
      run: mvn -B clean install -DskipTests
    
    # Exécuter les tests du module core
    - name: Run tests for core module
      run: mvn -B test -pl itexpert-content-core
    
    # Analyse SonarQube pour chaque module (depuis la racine avec -f)
    - name: 🔍 SonarQube Scan - Lib
      run: mvn -f itexpert-content-lib/pom.xml sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
    
    - name: 🔍 SonarQube Scan - Core
      run: mvn -f itexpert-content-core/pom.xml sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
    
    - name: 🔍 SonarQube Scan - API
      run: mvn -f itexpert-content-api/pom.xml sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
    
    - name: 🔍 SonarQube Scan - Studio
      run: mvn -f itexpert-content-ui/pom.xml sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
